name: mirror-repo

on: [ push, delete, create ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@bitbucket.org:rayyildiz/aras.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
